name: admin
description: A new Flutter project.

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  fl_chart: ^0.68.0
  provider: ^6.1.2
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  firebase_storage: 11.5.1
  get_storage: 2.0.3
  get: ^4.6.6
  url_strategy: ^0.3.0
  intl: ^0.18.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
